### ISSUE TITLE
Cant install from plugin

### ISSUE THREAD

**Issue by Wamy-Dev** [1stian/WindowsGSM.DeadMatter#1]
It wont let me install the server from the plugin. Says "Fail to Install [ERROR]"

**Comment by 1stian** [comment]
Ehm, you own the game?

**Comment by Wamy-Dev** [comment]
I do

**Comment by 1stian** [comment]
Okay, does it start downloading or does it fail before that?


Mvh
Stian

________________________________

**Comment by Wamy-Dev** [comment]
Fails before it. I just push the button and it fails

**Comment by 1stian** [comment]
Okay, I'll take a look, I've checked all the version I have of this. And they seem to all fail. And I know they've all worked before. Maybe the devs of the game has changed something.

**Comment by 1stian** [comment]
Nvm, you must hit "set account" first.. And complete that step first.

**Comment by Wamy-Dev** [comment]
Okay just did that and it works! thanks so much

**Comment by 1stian** [comment]
Np man :) I just couldn't think of what broke it.. And I remembered that usually happens if it doesn't have any username and password :D
